local M = {}

function M.highlights(c, opts)
  opts = opts or {}
  local groups = {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_float },
    FloatBorder = { fg = c.subtle, bg = c.bg_float },
    FloatTitle = { fg = c.accent, bg = c.bg_float, bold = true },

    Comment = { fg = c.comment, italic = true },
    Constant = { fg = c.accent },
    String = { fg = c.fg_alt },
    Character = { fg = c.fg_alt },
    Number = { fg = c.red },
    Boolean = { fg = c.red },
    Float = { fg = c.red },
    Identifier = { fg = c.fg_alt },
    Variable = { fg = c.fg_alt },
    Function = { fg = c.accent },
    Statement = { fg = c.magenta },
    Conditional = { fg = c.magenta },
    Repeat = { fg = c.magenta },
    Label = { fg = c.magenta },
    Operator = { fg = c.subtle },
    Keyword = { fg = c.comment },
    Exception = { fg = c.red },
    PreProc = { fg = c.accent_dark },
    Include = { fg = c.blue },
    Define = { fg = c.accent_dark },
    Macro = { fg = c.accent_dark },
    PreCondit = { fg = c.blue },
    Type = { fg = c.fg_alt },
    StorageClass = { fg = c.comment },
    Structure = { fg = c.fg_alt },
    Typedef = { fg = c.fg_alt },
    Special = { fg = c.accent },
    SpecialComment = { fg = c.comment, italic = true },
    Todo = { fg = c.bg, bg = c.accent, bold = true },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Error = { fg = c.error },
    ErrorMsg = { fg = c.error, bold = true },
    WarningMsg = { fg = c.warning },
    MoreMsg = { fg = c.hint },
    ModeMsg = { fg = c.accent, bold = true },
    Question = { fg = c.accent },

    LineNr = { fg = c.subtle },
    CursorLineNr = { fg = c.accent, bold = true },
    SignColumn = { fg = c.subtle, bg = c.bg },
    FoldColumn = { fg = c.subtle, bg = c.bg },
    Folded = { fg = c.fg_dim, bg = c.bg_alt },
    CursorLine = { bg = c.cursorline },
    CursorColumn = { bg = c.cursorline },
    ColorColumn = { bg = c.bg_alt },
    Cursor = { fg = c.bg, bg = c.cursor },
    MatchParen = { fg = c.accent, underline = true, bold = true },
    Visual = { bg = c.visual },
    VisualNOS = { bg = c.visual },
    Search = { fg = c.bg, bg = c.accent },
    IncSearch = { fg = c.bg, bg = c.accent_dark },
    Substitute = { fg = c.bg, bg = c.orange },
    QuickFixLine = { bg = c.bg_alt },
    ColorScheme = { fg = c.accent },

    StatusLine = { fg = c.fg, bg = c.bg_alt },
    StatusLineNC = { fg = c.fg_dim, bg = c.bg_alt },
    WinSeparator = { fg = c.bg_alt },
    VertSplit = { fg = c.bg_alt },
    TabLine = { fg = c.fg_dim, bg = c.bg_alt },
    TabLineSel = { fg = c.accent, bg = c.bg },
    TabLineFill = { fg = c.bg_alt, bg = c.bg_alt },
    WildMenu = { fg = c.bg, bg = c.accent },

    Pmenu = { fg = c.fg, bg = c.bg_alt },
    PmenuSel = { fg = c.bg, bg = c.accent },
    PmenuSbar = { bg = c.bg_alt },
    PmenuThumb = { bg = c.comment },

    DiffAdd = { fg = c.git_add, bg = c.diff_add },
    DiffChange = { fg = c.git_change, bg = c.diff_change },
    DiffDelete = { fg = c.git_delete, bg = c.diff_delete },
    DiffText = { fg = c.accent, bg = c.diff_text },

    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.info, undercurl = true },
    SpellLocal = { sp = c.hint, undercurl = true },
    SpellRare = { sp = c.magenta, undercurl = true },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.green },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.diff_change },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_alt },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_alt },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiagnosticSignError = { fg = c.error },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticSignInfo = { fg = c.info },
    DiagnosticSignHint = { fg = c.hint },

    LspReferenceText = { bg = c.selection },
    LspReferenceRead = { bg = c.selection },
    LspReferenceWrite = { bg = c.selection },
    LspSignatureActiveParameter = { fg = c.accent },

    CursorHold = { bg = c.cursorline },
    CursorHoldI = { bg = c.cursorline },

    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.git_change },
    GitSignsDelete = { fg = c.git_delete },

    TelescopeSelection = { fg = c.accent, bg = c.visual },
    TelescopeSelectionCaret = { fg = c.accent },
    TelescopeBorder = { fg = c.subtle, bg = c.bg },
    TelescopePromptBorder = { fg = c.subtle, bg = c.bg },
    TelescopeResultsBorder = { fg = c.subtle, bg = c.bg },
    TelescopePreviewBorder = { fg = c.subtle, bg = c.bg },
    TelescopePromptPrefix = { fg = c.accent },

    RainbowDelimiterYellow = { fg = c.accent },
    RainbowDelimiterBlue = { fg = c.blue_bright },
    RainbowDelimiterViolet = { fg = c.magenta },
    RainbowDelimiterOrange = { fg = c.comment },
    RainbowDelimiterGreen = { fg = c.accent_dark },
    RainbowDelimiterCyan = { fg = c.blue },
    RainbowDelimiterRed = { fg = c.red_soft },

    NvimTreeNormal = { fg = c.fg, bg = c.bg },
    NvimTreeNormalNC = { fg = c.fg, bg = c.bg },
    NvimTreeVertSplit = { fg = c.bg_alt, bg = c.bg },
    NvimTreeEndOfBuffer = { fg = c.bg },
    NvimTreeFolderName = { fg = c.fg_dim },
    NvimTreeFolderIcon = { fg = c.comment },
    NvimTreeOpenedFolderName = { fg = c.comment },
    NvimTreeGitNew = { fg = c.git_add },
    NvimTreeGitDirty = { fg = c.git_change },
    NvimTreeGitDeleted = { fg = c.git_delete },

    Terminal = { fg = c.fg, bg = c.bg },
  }

  ---@type table<string, vim.api.keyset.highlight>
  local treesitter = {
    ["@comment"] = { link = "Comment" },
    ["@constant"] = { fg = c.accent },
    ["@constant.builtin"] = { fg = c.accent },
    ["@constant.macro"] = { fg = c.accent_dark },
    ["@string"] = { fg = c.fg_alt },
    ["@string.escape"] = { fg = c.orange_bright },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@float"] = { link = "Float" },
    ["@symbol"] = { fg = c.orange },
    ["@field"] = { fg = c.fg_alt },
    ["@property"] = { fg = c.fg_alt },
    ["@variable"] = { fg = c.fg_alt },
    ["@variable.builtin"] = { fg = c.accent },
    ["@variable.parameter"] = { fg = c.fg_dim },
    ["@variable.member"] = { fg = c.fg_alt },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.accent },
    ["@function.macro"] = { fg = c.accent_dark },
    ["@method"] = { link = "Function" },
    ["@constructor"] = { fg = c.accent },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.comment },
    ["@keyword.operator"] = { link = "Operator" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@type"] = { fg = c.fg_alt },
    ["@type.builtin"] = { fg = c.accent },
    ["@type.definition"] = { link = "Typedef" },
    ["@namespace"] = { fg = c.fg_dim },
    ["@punctuation"] = { fg = c.comment },
    ["@punctuation.bracket"] = { fg = c.comment },
    ["@punctuation.delimiter"] = { fg = c.comment },
    ["@operator"] = { link = "Operator" },
    ["@tag"] = { fg = c.accent },
    ["@tag.attribute"] = { fg = c.comment },
    ["@tag.delimiter"] = { fg = c.subtle },
    ["@text"] = { fg = c.fg },
    ["@text.literal"] = { fg = c.fg },
    ["@text.reference"] = { fg = c.fg },
    ["@markup.heading"] = { fg = c.fg },
    ["@text.title"] = { fg = c.fg },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.accent },
    ["@markup.link.label"] = { fg = c.blue },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.list"] = { fg = c.accent },
    ["@markup.raw"] = { fg = c.orange },
    ["@markup.quote"] = { fg = c.comment },
    ["@comment.todo"] = { link = "Todo" },
  }

  for group, spec in pairs(treesitter) do
    groups[group] = spec
  end

  if opts.transparent then
    local transparent_groups = {
      Normal = true,
      NormalNC = true,
      NormalFloat = true,
      FloatBorder = true,
      FloatTitle = true,
      SignColumn = true,
      FoldColumn = true,
      Folded = true,
      StatusLine = true,
      StatusLineNC = true,
      TabLine = true,
      TabLineSel = true,
      TabLineFill = true,
      WildMenu = true,
      Pmenu = true,
      PmenuSel = true,
      PmenuSbar = true,
      PmenuThumb = true,
      NvimTreeNormal = true,
      NvimTreeNormalNC = true,
      NvimTreeVertSplit = true,
      TelescopeBorder = true,
      TelescopePromptBorder = true,
      TelescopeResultsBorder = true,
      TelescopePreviewBorder = true,
      Terminal = true,
    }

    for group in pairs(transparent_groups) do
      if groups[group] then
        groups[group].bg = "none"
      end
    end
  end

  return groups
end

return M
